[package]
name = "pokisona-markdown"
version.workspace = true
edition = "2024"

[dependencies]
bitflags = "2.9.3"
pest = "2.8.2"
serde_yml = "0.0.12"
pest_derive = { version = "2.8.2", features = ["grammar-extras"]}
yoke.workspace = true
itertools.workspace = true
