[workspace]
members = ["pokisona", "pokisona-markdown"]
default-members = ["pokisona"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
pokisona-markdown.path = "./pokisona-markdown"
yoke = { version = "0.8.0", features = ["derive"] }
itertools = "0.14.0"
